name: gdbs_ml

services:
  db:
    image: postgres:alpine3.20
    environment:
      - POSTGRES_USER=$POSTGRES_USERNAME
      - POSTGRES_DB=$POSTGRES_DATABASE
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USERNAME"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./minio_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
    
  back:
    container_name: back
    image: elecshen/gdbs_back:dev
    environment:
      - ASPNETCORE_URLS=$ASPNETCORE_URLS
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
      - DB_CONNECTION_STRING=$DB_CONNECTION_STRING
      - MINIO_ENDPOINT=$MINIO_ENDPOINT
      - MINIO_ACCESS_KEY=$MINIO_ACCESS_KEY
      - MINIO_SECRET_KEY=$MINIO_SECRET_KEY
      - MINIO_BUCKET=$MINIO_BUCKET
    ports:
      - '5000:80'
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    
  pgadmin:
    container_name: pg
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 1234@a.ru
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - '80:80'
    depends_on:
      db:
        condition: service_healthy
        
volumes:
  pgadmin: